export default{
    data(){
        return{
            searchData:[
                {
                    label:'类型',
                    prop:'type',
                    type:'text'
                },
                {
                    label:'时间',
                    prop:'date',
                    type:'daterange'
                },
                {
                    label:'测试',
                    prop:'test',
                    type:'select',
                    option:[
                        {
                            label:'测试1',
                            value:'1'
                        },
                        {
                            label:'测试2',
                            value:'2'
                        }
                    ]
                }
            ]
        }
    }
}